export const TITLE = "Editar Producto";
export const NAME_PRODUCT = "Nombre del Producto";
export const PRICE = "Precio Venta";
export const COST = "Precio Costo";
export const IVA = "IVA";
export const CATEGORY = "Categoría"
export const DESCRIPTION = "Descripción";
export const CODE = "Código";
export const AMOUNT = "Cantidad";
export const FAIL = "CANCELAR";
export const DONE = "CONFIRMAR";