export const TITLE = "Registro de Productos";
export const NAME_PRODUCT = "Nombre del Producto";
export const PRICE = "Precio";
export const CODE = "Código";
export const AMOUNT = "Cantidad";
export const IVA = "IVA"
export const CATEGORY = "Categoría del Producto";
export const DESCRIPTION = "Descripción del Producto";
export const SAVE = "GUARDAR";